//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public department()
        {
            this.disbursements = new HashSet<disbursement>();
            this.requisitions = new HashSet<requisition>();
            this.users = new HashSet<user>();
        }
    
        public string departmentId { get; set; }
        public string name { get; set; }
        public string contactName { get; set; }
        public Nullable<decimal> phoneNo { get; set; }
        public Nullable<decimal> faxNo { get; set; }
        public string collectionPointId { get; set; }
    
        public virtual collectionPoint collectionPoint { get; set; }
        public virtual ICollection<disbursement> disbursements { get; set; }
        public virtual ICollection<requisition> requisitions { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
