//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.disbursementDetails = new HashSet<disbursementDetail>();
            this.discrepancies = new HashSet<discrepancy>();
            this.purchaseOrderDetails = new HashSet<purchaseOrderDetail>();
            this.reorderItems = new HashSet<reorderItem>();
            this.requisitionDetails = new HashSet<requisitionDetail>();
            this.supplierPrices = new HashSet<supplierPrice>();
        }
    
        public string itemId { get; set; }
        public string categoryId { get; set; }
        public string uomId { get; set; }
        public string description { get; set; }
        public Nullable<int> reorderLevel { get; set; }
        public Nullable<int> reorderQty { get; set; }
        public Nullable<int> stockBalance { get; set; }
        public string status { get; set; }
        public string binNumber { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<disbursementDetail> disbursementDetails { get; set; }
        public virtual ICollection<discrepancy> discrepancies { get; set; }
        public virtual uomeasure uomeasure { get; set; }
        public virtual ICollection<purchaseOrderDetail> purchaseOrderDetails { get; set; }
        public virtual ICollection<reorderItem> reorderItems { get; set; }
        public virtual ICollection<requisitionDetail> requisitionDetails { get; set; }
        public virtual ICollection<supplierPrice> supplierPrices { get; set; }
    }
}
