//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public menu()
        {
            this.menuByRoles = new HashSet<menuByRole>();
        }
    
        public int menuId { get; set; }
        public string parentId { get; set; }
        public string menu1 { get; set; }
        public string url { get; set; }
    
        public virtual ICollection<menuByRole> menuByRoles { get; set; }
    }
}
