//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseOrderDetail
    {
        public string purchaseOrderId { get; set; }
        public string itemId { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<double> amount { get; set; }
    
        public virtual item item { get; set; }
        public virtual purchaseOrder purchaseOrder { get; set; }
    }
}
