//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public supplier()
        {
            this.discrepancies = new HashSet<discrepancy>();
            this.purchaseOrders = new HashSet<purchaseOrder>();
            this.reorderItems = new HashSet<reorderItem>();
            this.supplierPrices = new HashSet<supplierPrice>();
        }
    
        public string supplierId { get; set; }
        public string name { get; set; }
        public string contactName { get; set; }
        public Nullable<decimal> phoneNo { get; set; }
        public Nullable<decimal> faxNo { get; set; }
        public string address { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<discrepancy> discrepancies { get; set; }
        public virtual ICollection<purchaseOrder> purchaseOrders { get; set; }
        public virtual ICollection<reorderItem> reorderItems { get; set; }
        public virtual ICollection<supplierPrice> supplierPrices { get; set; }
    }
}
