//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class uomeasure
    {
        public uomeasure()
        {
            this.items = new HashSet<item>();
        }
    
        public string uomId { get; set; }
        public string uom { get; set; }
        public Nullable<int> number { get; set; }
    
        public virtual ICollection<item> items { get; set; }
    }
}
